language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
    recipients:
    - june0313@gmail.com
    on_success: always
    on_failure: always
branches:
  only:
  - master
before_install:
- gem install travis -v 1.8.9 --no-document
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=chapter10-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
- export CONTAINER_IP=13.209.85.62
- export PLATFORM_TEST_NAME="chapter10-platform-tests"
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
env:
  global:
  - NO_GCE_TEST=true
  - secure: CXJLTuGa5FawGseIxKzJmr1BNU0qhZQ2c/DZrDhz5d0YdYl10Wd3wbxzCsl13Lhin2Dheaa7A2wDZlvh7lyqohOzrFVwlTUZ7TC5TXxlVM00FVKldVPmyoxb+jv2VsujsAo4AtUG9Rkm0U1H8eWHeRkzXo2kTFFy1cYS2vcacV7gvf2UzbXPv8yZ8fCulK4dAfKaWx68KijBN5pyq1hclKei4VJz5DspfKLXRgUnO43cgPw2ylK8JGP8YBOw8HwrAVOgi+9aSD5B9rgkqSWwg6qP9Jvevry+yuIj7vjsBTMrf3ox/lLp/8okP9JAaHGHBxgT+ufBN2OB9JDtmgYY6dmvJHf4HdDG7CCClR7o/0hvLhWDVmU+J66QXIUXGR+88dbDSFBkAKYR/uGgAG8ejVq8L8qj0AJiYBg9aDVSR3Ys3r8OI6ATcQpNtE4qgu3nWiOxYLFuWuZOChFElwmRaIVUfhgimlZGjhWeLJtI8dtILg1hYYU5yTTB15kpsLAeYI9czmW08ewRV58oJpgj/dcRdoqD+diznfmuQfbLkGtWclW4+hW4vUQ+hn2dJ6RpsykqzYqlICvBKnEdYuFHSbITN2m/tTuvYEMC/WfLQEKZJsd52cwvGr3tcqq90R9qcOZTHTyyIgNHXlvWfJg68ReGTEZfTEbQI8nA32R9Ihc=
  - secure: a/w4fFD9nzMmUo++zYkhyMg4leySGvaNmy1RIHusl3iqKMWXqquQPueiu93wRkm6AN5C+qkaeRzYI9XNOD2uzCDipQMHFDXZbM5+yyUOC6TSEBmnT/0StJAI++D2Ryt89Jiblc1uxp9URycMi9+z1DV8U2Pg7PUE9TOqjH6CAiKP5k+KEpvJOlbF2ZxMJH1s7j+4RRh5vpCLM6iOuPJBJMEcHiNgqeMr6NHUqMMRsYTP/HNTPYdRRCo0pfQbW13JwA93a42nc3Z/DES82upp3Uf3137frovHMdMK5+mhyqhwSpgqETlRFC0jB+SFS3ACWV0064ZjQp3vPx/RSUio1pBDEHFFMsm8qhQbOOxfNnQa5Eop4JW3DCyqKOA+5JOe3TXJ9hzWb39vh+u7ryQCoKzof7x3vhuU4YGEpQ6HvRQVVXHmWSXT+K3dTwq9YofAWC1n6rNydf9kcYMKDMq5pBdOIMkDTMd9h720VS2ArpOZBswj19v+JnY7Ar4u/Nmb4vLidhVeqTiKWD1JVNDRW27NzaEXS3N3YN2aBaqsMgePmbk1lGjU/AwvIp5uQp0Ns8ORvStkBiTghWUdzv//dG8XZKm40SIgUKn81UkijuN3z+BlBTB+XrZ50D9xGVvJ+Hx91SzrMKKSTTMvyRi1wb4lKfGuYWDUS6cNeCdIi6A=
  - secure: d5W4LTSp9gylSeTe0EvbAT0O3HK0vdRN5/bUcerFNe2wPSsDHUQgwOJmD6/dIj636tXj1wU04NmsIekPrar4xngUmDcaRKg44edpdXm8qZ9BT/553ClRAQSTZdpXqbROHvXJKPCriePc8ql2AQmqSKWvY+4mRoqE4421gIeBB0eJ8PAxX7/10f562HyG58IweVAhQToEHu+gjfKiWRx+POMWL8v0L5r08usqJ86GHrytCJm93epKUt8oBfslOEIHlGliRbMfhphDoXXyINP4C6WMP9HrMzaV8LfU2+G/f6V2oflxbXugi2zSuO3ahBtKs63BMIT497hLdwdVe6Lp6Me/dA91G0gMTq31A5EgCRpR+b7+2lok4y1AT8FrLRYuocD1DDRfivTIH4yTtHoHkJacdj3GkRApb/d3NpSCqFdC/VBsKjeeqBc5nGKTLP9sIdvUbcDrrqN/cUsd0ZZ9ZLPb+ZnoPe8IGm3fQvBGQASCI1pBCF4ygNJDsZYjx560fHelBOwMilcKDvUhKIQwBOJG9moWgxvr+QwfZ/wW8taexPJVZdPtFYuayUYWGJNhTGUX36kZkk3Ye6A6ZqWUeo9LHes2M982wLvP2zC6HcB/6BiU4OaNxNnTvVFT/hAQ1It5msIgN4EOVRoQatLLdghvxMeA/sSsvc0Vq5btWMY=
  - secure: egyHemknojf1WyScEBSb5d1Ublk8GFlZr+0dqw1BiGlkW3oALpUkJHfD2s3LrbKruXpUnXPAXHLu8/EZ2ucRStTDBN+Elt5b57GZxKBcAT6b4lB7LjIMUYFWbnaXNRftwvx/kRtxN+ZCPUME+IcHwhiXcrzeQoROjEHWdZI6vMlSjgGTELThGISIf2sSq0W6jKKHxMnx/pvoX8OlzIwO5H/zvKz3azqfpWTdlVmLYeCy0gzxu2Nn+WPqty3UhTjALEN5gVTeAJVFRUy7htQ6kLHTq/9hDh7dgiSG2DZhAC0vX3LWnAfff6d/rrjigTf+nkjtjBrpJFPZ0OiwALWhlhUIO/QHmTiZDfDqORUd2HxsP0xBDGQnn3KEEP3sUZsp6RhTWxYM0BcOxeS8hmvNnJFYJ80nCnrspQaSrxiQz+j7n+5QAeLydreQcUYImiDcO6RBYfYYZoZqnuk3BFqbXY9woZEMpkcAlDpi6gqPXHUUJ99yNmxJqgmTdg8f8KAAdMxBaTYPogwKuWxgYqYFvqDv4wS3jOzlTCGfZx2kPh7EWr0NYtldgqlQ+XR16Vo5HGeyywi8RLMYVyV3cp0cdMg+19It+OW6d+Ni8xg0CnVXf//Rujl//gG6OaZftjPjCNIqqik4YOBdzjLTk24wByK7msxna4Ifj5a6wFDL/WE=
  - secure: seYvT9WsObkD/S119blCwOh1MJ2Xi+9DNcx5QSVmeD/7AgGCnP6jpwhlJ8jcIbg41CziPWCoryCd2nkLnVnVaHvHgHceyfNp+DnAi4i7GdekeQcMrxeonYNVd9WIx6TtL75ftpN/ROvJgkPH5EGRrSj2nqCcWxMJ8St6QyuTdePXokXeHzx9mFNSpbue6WfdHw2mpe0XnbD0yz75/hD9jUXy7iE2UYkO2TGVjY8o4HOvaa8mYfmQzD/ka6Kt7OhdRJ0j8TwYF62XuK0M47K4SMueTc9EOPDU39uy5fGvJoUi1eq6kVys37tSEK3nWadKqQwQOFUQqEcs9UouO6Ofp1Q30bvPUJGhktBv6/kwfYcPawr9E/WDT+iNVF8GAAtOJfvOcx2lFe/BT+aADYoVoAy/1S7x4vGpIV+eCpT0l+ycn3lcTGohBC4OjCNi+MJmBWla/mEsCcBKjDEvp1ffFqM/z0B1Qv26RHrUH4gRyEGUgpQ/49orvBts4jM5ofiPX1y+zVY/zF/y03H/OOKf1WDnAMTI1OEZdj94lxCKTeVmlzfCqqhrheeY+fJwFcL1R3HRGYcJ3ojWF2opJrN0Dlf4GUeC5m2uZ8jgYwgbF9qVsPdxRZd/y10vgk//R1HtlsT8OmTzfsl4wCnOB7dVq0kt+lHMJYva5eG212YwBco=
